org: parthparadkar
app: hive
service: serverless-hive

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:*
          Resource: "*"

        - Effect: Allow
          Action: dynamodb:*
          Resource: "*"
  environment:
    S3_BUCKET: hive-emails
    EMAILS_TABLE: hive-emails-db

functions:
  receiveEmail:
    handler: index.handler
    events:
      - s3:
          bucket: ${self:provider.environment.S3_BUCKET}
          event: s3:ObjectCreated:*
          existing: true
  
  allBookmarks:
    handler: api.handler
    events:
      - http: 'GET /bookmarks'

  deleteBookmark:
    handler: api.handler
    events:
      - http: 'DELETE /bookmarks/delete/{proxy+}'

  getBookmarkbyId:
    handler: api.handler
    events:
      - http: 'GET /bookmark/{proxy+}'

  addBookmarkNote:
    handler: api.handler
    events:
      - http: 'POST /notes/add'

resources:
  Resources:
    EmailsTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: s3Key
            AttributeType: S
        KeySchema:
          - AttributeName: s3Key
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.EMAILS_TABLE}